#!/usr/bin/env python3
import parasail
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AUTOGEN_INCLUDE_FILE = ROOT / "code/include/generated/bio/score/matrices.h"

AMINO_ALPHABET = "ARNDCQEGHILKMFPSTWYVBZX*"
NUCLEO_ALPHABET = "ATGCSWRYKMBVHDN*"
STRIDE = len(AMINO_ALPHABET)

AMINO_LUT = [-1] * 128
for index, letter in enumerate(AMINO_ALPHABET):
    AMINO_LUT[ord(letter)] = index

NUCLEO_LUT = [-1] * 128
for index, letter in enumerate(NUCLEO_ALPHABET):
    NUCLEO_LUT[ord(letter)] = index

lines = []
for name, lut in (("AMINO_LUT", AMINO_LUT), ("NUCLEO_LUT", NUCLEO_LUT)):
    lines.append(f"static const s32 {name}[SEQ_LUT_SIZE] = {{")
    for i in range(0, len(lut), 16):
        row = lut[i : i + 16]
        row_values = ", ".join(f"{value:>3}" for value in row)
        lines.append(f"{row_values},")
    lines.append("};\n")
lut_block = "\n".join(lines)

AMINO_MATRICES = []
NUCLEO_MATRICES = []

for matrix in sorted(attr for attr in dir(parasail) if not attr.startswith("__")):
    is_amino = matrix.startswith(("blosum", "pam"))
    is_nucleo = matrix in ("dnafull", "nuc44")
    if not is_amino and not is_nucleo:
        continue

    matrix_obj = getattr(parasail, matrix)
    raw = getattr(matrix_obj, "matrix", None)
    if raw is None:
        continue

    if is_amino:
        alphabet = AMINO_ALPHABET
        target = AMINO_MATRICES
        lut_name = "AMINO_LUT"
    elif is_nucleo:
        alphabet = NUCLEO_ALPHABET
        target = NUCLEO_MATRICES
        lut_name = "NUCLEO_LUT"
    else:
        continue

    size = len(alphabet)
    values = [[int(raw[i][j]) for j in range(size)] for i in range(size)]
    data = list(zip(alphabet, values))
    target.append((matrix, matrix.upper(), lut_name, data))

lines = []
lines.append(f"#define AMINO_MAT_N ({len(AMINO_MATRICES)})")
lines.append(f"#define NUCLEO_MAT_N ({len(NUCLEO_MATRICES)})\n")
for matrices in (AMINO_MATRICES, NUCLEO_MATRICES):
    for _, symbol, _, data in matrices:
        lines.append(f"static const s32 {symbol}[SUB_MAT_DIM * SUB_MAT_DIM] = {{")
        lines.extend(
            [
                f"[{row_index * STRIDE:>3}] = {', '.join(f'{value:>3}' for value in row)}, /* {letter} */"
                for row_index, (letter, row) in enumerate(data)
            ]
        )
        lines.append("};\n")

lines.append("static const matrix MATRICES[] = {")
for matrices in (AMINO_MATRICES, NUCLEO_MATRICES):
    for name, symbol, lut_name, _ in matrices:
        lines.append(f'{{"{name}", {symbol}, {lut_name}}},')
lines.append("};")
matrices_block = "\n".join(lines)

autogen_include_content = (
    "/* Auto-generated by script/generate_matrices.py. Do not edit manually. */\n"
    "#ifdef GENERATED_MATRICES_IMPLEMENTATION\n"
    "/* clang-format off */\n"
    f"{lut_block}\n"
    f"{matrices_block}\n"
    "/* clang-format on */\n"
    "#endif /* GENERATED_MATRICES_IMPLEMENTATION */\n"
)

os.makedirs(AUTOGEN_INCLUDE_FILE.parent, exist_ok=True)
with open(AUTOGEN_INCLUDE_FILE, "w") as f:
    f.write(autogen_include_content)
print(f"Generated {AUTOGEN_INCLUDE_FILE}")
