#!/usr/bin/env python3
import parasail
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AUTOGEN_INCLUDE_FILE = ROOT / "include/generated/bio/score/matrices.h"

AMINO_ALPHABET = "ARNDCQEGHILKMFPSTWYVBZX*"
NUCLEO_ALPHABET = "ATGCSWRYKMBVHDN*"
STRIDE = len(AMINO_ALPHABET)
AMINO_PREFIXES = ("blosum", "pam")
NUCLEO_PREFIXES = ("dna", "nuc")

AMINO_NAMES, AMINO_MATRICES = [], []
NUCLEO_NAMES, NUCLEO_MATRICES = [], []

for name in sorted(attr for attr in dir(parasail) if not attr.startswith("__")):
    if name.startswith(AMINO_PREFIXES):
        names, matrices, alphabet = AMINO_NAMES, AMINO_MATRICES, AMINO_ALPHABET
    elif name.startswith(NUCLEO_PREFIXES):
        names, matrices, alphabet = NUCLEO_NAMES, NUCLEO_MATRICES, NUCLEO_ALPHABET
    else:
        continue

    if (raw := getattr(getattr(parasail, name), "matrix", None)) is None:
        continue

    names.append(name)
    size = len(alphabet)
    matrices.append([[int(raw[i][j]) for j in range(size)] for i in range(size)])

NAMES = AMINO_NAMES + NUCLEO_NAMES
names_block = (
    "static const char *NAMES[AMINO_MAT_N + NUCLEO_MAT_N] = {"
    + ",".join(f'"{name}"' for name in NAMES)
    + "};"
)

LUT = [-1] * 128 * 2
for offset, alphabet in enumerate((AMINO_ALPHABET, NUCLEO_ALPHABET)):
    for index, letter in enumerate(alphabet):
        LUT[ord(letter) + offset * 128] = index

lut_block = (
    f"static const s32 LUT[SEQ_LUT_SIZE * 2] = {{{','.join(str(n) for n in LUT)}}};"
)

matrix_entries = [
    str(value) for values in AMINO_MATRICES for row in values for value in row
]

nucleo_start = len(AMINO_MATRICES) * STRIDE * STRIDE
matrix_entries.extend(
    f"[{nucleo_start + (matrix_index * STRIDE * STRIDE) + (row_index * STRIDE)}]="
    + ",".join(str(value) for value in row)
    for matrix_index, values in enumerate(NUCLEO_MATRICES)
    for row_index, row in enumerate(values)
)

matrices_block = (
    "static const s32 MATRICES[SUB_MAT_DIM * SUB_MAT_DIM * (AMINO_MAT_N + NUCLEO_MAT_N)] = {"
    + ",".join(matrix_entries)
    + "};"
)

autogen_include_content = "\n".join(
    (
        "/* Auto-generated by script/generate_matrices.py. Do not edit manually. */",
        "#ifdef GENERATED_MATRICES_IMPLEMENTATION",
        "/* clang-format off */",
        f"#define AMINO_MAT_N ({len(AMINO_MATRICES)})",
        f"#define NUCLEO_MAT_N ({len(NUCLEO_MATRICES)})",
        f"#define NAMES_LONGEST ({max(len(name) for name in NAMES)})",
        names_block,
        lut_block,
        matrices_block,
        "/* clang-format on */",
        "#endif /* GENERATED_MATRICES_IMPLEMENTATION */",
        "",
    )
)

AUTOGEN_INCLUDE_FILE.parent.mkdir(parents=True, exist_ok=True)
AUTOGEN_INCLUDE_FILE.write_text(autogen_include_content)
print(f"Generated {AUTOGEN_INCLUDE_FILE}")
