name: Sync Dev with Main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Sync dev with main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push origin main:dev --force