name: Test for errors

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up apt cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libhdf5-dev
          version: 1.0 # change this to clear the cache and reinstall the packages
      
      - name: Build
        run: make
      
      - name: Run test
        run: bin/seqalign -i datasets/avppred.csv -t amino -a nw -m blosum62 -p 4 -B -v