name: Test for errors

on:
  repository_dispatch:
    types: [run-daily-workflows]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up apt cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libhdf5-dev
          version: 1.0
      
      - name: Build
        run: make
      
      - name: Run test
        run: bin/seqalign -i datasets/avppred.csv -t amino -a nw -m blosum62 -p 4 -B -v -D
