name: Test for errors

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-daily-workflows]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up apt cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake ninja-build build-essential libhdf5-dev
          version: 1.0

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja \
            -DUSE_CUDA=OFF \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DARCH_LEVEL=native

      - name: Build
        run: cmake --build build --config RelWithDebInfo -- -j$(nproc)

      - name: Run test
        run: ./bin/seqalign -i datasets/avppred.csv -t amino -a nw -m blosum62 -p 4 -B -v -D
